Add director
VanDerIv/java-filmorate pull request #12
Opened 2023-04-15 12:11 UTC by RailgunSinon

Там есть костыль на старый функционал. Остальное все прошло тесты, и по ручному тестированию не падало. Но если будут кейсы у кого - скажите.

2023-04-15 17:44 UTC, VanDerIv approved these changes

2023-04-16 07:04 UTC, andrey-rastorguev requested changes

2023-04-16 10:30 UTC, RailgunSinon commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    DirectorService directorService;
Просглядел, спасибо

2023-04-16 10:30 UTC, RailgunSinon commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      @Autowired
Аннотация не лишняя. Ее можно не указывать, но лучше(и правильно) всегда указывать.

2023-04-16 10:31 UTC, andrey-rastorguev approved these changes

2023-04-16 12:51 UTC, merged