ТЗ 11
VanDerIv/java-filmorate pull request #7
Opened 2023-03-09 13:21 UTC by VanDerIv

2023-03-09 20:28 UTC, db-exp requested changes

2023-03-09 20:28 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (films.size() == 0) {
лучше isEmpty, он оптимальней работает

2023-03-09 20:28 UTC, db-exp commented on src/main/resources/schema.sql
> +    email character varying(255) NOT NULL,
на email вряд ли нужно 255

2023-03-10 05:56 UTC, VanDerIv commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    @Autowired
знаю, но мне так нравится

2023-03-10 05:59 UTC, VanDerIv commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        if (rating == null) throw new NotFoundException(String.format("Рейтинг %d не найден", id));
поправлю, хотя мне очень нравятся однострочные, когда они не большие и в них только одна команда. Не понимаю как это может привезти к проблеме какой бы большой и старый код не был.

2023-03-10 13:30 UTC, merged