feat: тз12 Функциональность «Отзывы»
VanDerIv/java-filmorate pull request #8
Opened 2023-04-11 18:55 UTC by VanDerIv

2023-04-15 12:46 UTC, RailgunSinon approved these changes

2023-04-16 02:39 UTC, andrey-rastorguev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +
Если используется конструктор, то аннотация @Autowired не нужна. Все будет нормально без нее работать. Либо одно либо другое желательно использовать. Также анотация @AllArgsConstructor перед классом позволяет убрать конструктор в явном виде. В итоге получится более лаконичный код

2023-04-16 02:40 UTC, andrey-rastorguev commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +
Тоже можно использовать @AllArgsConstructor без @Autowired

2023-04-16 02:42 UTC, andrey-rastorguev commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private final JdbcTemplate jdbcTemplate;
В данном случае SQL константа, а константы пишутся полностью прописными буквами

2023-04-16 02:42 UTC, andrey-rastorguev commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +
@Autowired тут не нужна, так как есть конструктор

2023-04-16 02:47 UTC, andrey-rastorguev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +
Если используется конструктор, то аннотация @Autowired не нужна. Все будет нормально без нее работать. Тут либо одно либо другое желательно использовать. Также анотация @AllArgsConstructor перед классом позволяет убрать конструктор в явном виде. В итоге получится более лаконичный код

2023-04-16 02:47 UTC, andrey-rastorguev commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +
Тоже можно использовать @AllArgsConstructor без @Autowired

2023-04-16 02:48 UTC, andrey-rastorguev commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +
В данном случае SQL константа, а константы пишутся полностью прописными буквами

2023-04-16 02:48 UTC, andrey-rastorguev commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +
Аннотация @Autowired тут не нужна, так как есть конструктор

2023-04-16 07:03 UTC, andrey-rastorguev requested changes

2023-04-16 07:04 UTC, VanDerIv commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    @Autowired
Нужна, потому что это признак хорошего тона в программировании явно указывать @Autowired

2023-04-16 07:05 UTC, VanDerIv commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private final String sql = "SELECT r.*, NVL(rs.score, 0) score " +
SQL не константа, т.к. у нее нет признака static

2023-04-16 07:08 UTC, VanDerIv commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    @Autowired
Это сервис, а не энтити, он имеет паттерн синглтон, тут нет никакого смысла применять @AllArgsConstructor

2023-04-16 07:12 UTC, VanDerIv commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @Autowired
Лаконичный код не всегда хорошо, в случае с @AllArgsConstructor ты отдаешь на долю программы создать конструктор по всем аргументам, а если у тебя появятся лишние аргументы, которые не надо задавать? Это приведет к ошибкам. Я для синглтона такие аннотации как @AllArgsConstructor считаю скорей вредными чем полезными.

2023-04-16 07:16 UTC, andrey-rastorguev commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private final String sql = "SELECT r.*, NVL(rs.score, 0) score " +
По сути это константа https://ru.stackoverflow.com/questions/971250/%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B0-static-final-%D0%B8%D0%BB%D0%B8-%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE-final

2023-04-16 07:51 UTC, andrey-rastorguev approved these changes

2023-04-16 07:51 UTC, andrey-rastorguev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @Autowired
ну @AllArgsConstructor это скорей рекомендация как и все связанное с lombok

2023-04-16 07:58 UTC, VanDerIv commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private final String sql = "SELECT r.*, NVL(rs.score, 0) score " +
Если ты ее сделаешь SQL, то она не пройдет style ревью

2023-04-16 07:58 UTC, merged